### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by chenkasirer** [compas-dev/compas_occ#26]
**Describe the bug**

Must be missing in `requirements.txt`. 
It is currently breaking the `Brep` plugin behavior.

**To Reproduce**

```python
>>> from compas_occ.brep import OCCBrep
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ckasirer\anaconda3\envs\model_test\Lib\site-packages\compas_occ\brep\__init__.py", line 4, in <module>
    from .brepvertex import OCCBrepVertex  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ckasirer\anaconda3\envs\model_test\Lib\site-packages\compas_occ\brep\brepvertex.py", line 7, in <module>
    from compas_occ.conversions.geometry import point_to_occ
  File "C:\Users\ckasirer\anaconda3\envs\model_test\Lib\site-packages\compas_occ\conversions\__init__.py", line 51, in <module>
    from .meshes import compas_mesh_to_occ_shell
  File "C:\Users\ckasirer\anaconda3\envs\model_test\Lib\site-packages\compas_occ\conversions\meshes.py", line 19, in <module>
    from typing_extensions import Annotated
ModuleNotFoundError: No module named 'typing_extensions'
```
**Additional context**

**Comment by tomvanmele** [comment]
no actually it should be `from typing import Annotated`. will fix and re-release...

**Comment by Licini** [comment]
can we re-release this? having same error

**Comment by tomvanmele** [comment]
done
